name: Publish
on:
  push:
    tags: ["v*", "**/v*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"
          cache: true

      - name: Notify Go Proxy
        run: |
          TAG=${GITHUB_REF#refs/tags/}

          if [[ $TAG == *"/"* ]]; then
            DIR="${TAG%/*}"
            MODULE=$(cd $DIR && go list -m)
          else
            DIR="."
            MODULE=$(go list -m)
          fi

          echo "Publishing $MODULE at $TAG from directory $DIR"

          cd $DIR
          go test -v -race ./...

          VERSION=${TAG##*/}
          GOPROXY=https://proxy.golang.org go list -m ${MODULE}@${VERSION}
